#![doc = "Peripheral access API for AT32F423 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDT();
    fn PVM();
    fn TAMPER();
    fn ERTC_WKUP();
    fn FLASH();
    fn CRM();
    fn EXINT0();
    fn EXINT1();
    fn EXINT2();
    fn EXINT3();
    fn EXINT4();
    fn DMA1_CHANNEL1();
    fn DMA1_CHANNEL2();
    fn DMA1_CHANNEL3();
    fn DMA1_CHANNEL4();
    fn DMA1_CHANNEL5();
    fn DMA1_CHANNEL6();
    fn DMA1_CHANNEL7();
    fn ADC();
    fn CAN1_TX();
    fn CAN1_RX0();
    fn CAN_RX1();
    fn CAN_SE();
    fn EXINT9_5();
    fn TMR1_BRK_TMR9();
    fn TMR1_OVF_TMR10();
    fn TMR1_TRG_HALL_TMR11();
    fn TMR1_CH();
    fn TMR2();
    fn TMR3();
    fn TMR4();
    fn I2C1_EVT();
    fn I2C1_ERR();
    fn I2C2_EVT();
    fn I2C2_ERR();
    fn SPI1();
    fn SPI2();
    fn USART1();
    fn USART2();
    fn USART3();
    fn EXINT15_10();
    fn ERTCALARM();
    fn OTGFS1_WKUP();
    fn XMC();
    fn SPI3();
    fn USART4();
    fn USART5();
    fn TMR6();
    fn TMR7();
    fn CAN2_TX();
    fn CAN2_RX0();
    fn CAN2_RX1();
    fn CAN2_SE();
    fn OTGFS1();
    fn USART6();
    fn I2C3_EVT();
    fn I2C3_ERR();
    fn USART7();
    fn USART8();
    fn QSPI2();
    fn QSPI1();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 93] = [
    Vector { _handler: WWDT },
    Vector { _handler: PVM },
    Vector { _handler: TAMPER },
    Vector {
        _handler: ERTC_WKUP,
    },
    Vector { _handler: FLASH },
    Vector { _handler: CRM },
    Vector { _handler: EXINT0 },
    Vector { _handler: EXINT1 },
    Vector { _handler: EXINT2 },
    Vector { _handler: EXINT3 },
    Vector { _handler: EXINT4 },
    Vector {
        _handler: DMA1_CHANNEL1,
    },
    Vector {
        _handler: DMA1_CHANNEL2,
    },
    Vector {
        _handler: DMA1_CHANNEL3,
    },
    Vector {
        _handler: DMA1_CHANNEL4,
    },
    Vector {
        _handler: DMA1_CHANNEL5,
    },
    Vector {
        _handler: DMA1_CHANNEL6,
    },
    Vector {
        _handler: DMA1_CHANNEL7,
    },
    Vector { _handler: ADC },
    Vector { _handler: CAN1_TX },
    Vector { _handler: CAN1_RX0 },
    Vector { _handler: CAN_RX1 },
    Vector { _handler: CAN_SE },
    Vector { _handler: EXINT9_5 },
    Vector {
        _handler: TMR1_BRK_TMR9,
    },
    Vector {
        _handler: TMR1_OVF_TMR10,
    },
    Vector {
        _handler: TMR1_TRG_HALL_TMR11,
    },
    Vector { _handler: TMR1_CH },
    Vector { _handler: TMR2 },
    Vector { _handler: TMR3 },
    Vector { _handler: TMR4 },
    Vector { _handler: I2C1_EVT },
    Vector { _handler: I2C1_ERR },
    Vector { _handler: I2C2_EVT },
    Vector { _handler: I2C2_ERR },
    Vector { _handler: SPI1 },
    Vector { _handler: SPI2 },
    Vector { _handler: USART1 },
    Vector { _handler: USART2 },
    Vector { _handler: USART3 },
    Vector {
        _handler: EXINT15_10,
    },
    Vector {
        _handler: ERTCALARM,
    },
    Vector {
        _handler: OTGFS1_WKUP,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: XMC },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _handler: USART4 },
    Vector { _handler: USART5 },
    Vector { _handler: TMR6 },
    Vector { _handler: TMR7 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: CAN2_TX },
    Vector { _handler: CAN2_RX0 },
    Vector { _handler: CAN2_RX1 },
    Vector { _handler: CAN2_SE },
    Vector { _handler: OTGFS1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: USART6 },
    Vector { _handler: I2C3_EVT },
    Vector { _handler: I2C3_ERR },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: USART7 },
    Vector { _handler: USART8 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: QSPI2 },
    Vector { _handler: QSPI1 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Window Watchdog interrupt"]
    WWDT = 0,
    #[doc = "1 - PVM interrupt connect to EXINT line16"]
    PVM = 1,
    #[doc = "2 - Tamper interrupt connect to EXINT line21"]
    TAMPER = 2,
    #[doc = "3 - ERTC Global interrupt connect to EXINT line22"]
    ERTC_WKUP = 3,
    #[doc = "4 - Flash global interrupt"]
    FLASH = 4,
    #[doc = "5 - CRM global interrupt"]
    CRM = 5,
    #[doc = "6 - EXINT Line0 interrupt"]
    EXINT0 = 6,
    #[doc = "7 - EXINT Line1 interrupt"]
    EXINT1 = 7,
    #[doc = "8 - EXINT Line2 interrupt"]
    EXINT2 = 8,
    #[doc = "9 - EXINT Line3 interrupt"]
    EXINT3 = 9,
    #[doc = "10 - EXINT Line4 interrupt"]
    EXINT4 = 10,
    #[doc = "11 - DMA1 Channel1 global interrupt"]
    DMA1_CHANNEL1 = 11,
    #[doc = "12 - DMA1 Channel2 global interrupt"]
    DMA1_CHANNEL2 = 12,
    #[doc = "13 - DMA1 Channel3 global interrupt"]
    DMA1_CHANNEL3 = 13,
    #[doc = "14 - DMA1 Channel4 global interrupt"]
    DMA1_CHANNEL4 = 14,
    #[doc = "15 - DMA1 Channel5 global interrupt"]
    DMA1_CHANNEL5 = 15,
    #[doc = "16 - DMA1 Channel6 global interrupt"]
    DMA1_CHANNEL6 = 16,
    #[doc = "17 - DMA1 Channel7 global interrupt"]
    DMA1_CHANNEL7 = 17,
    #[doc = "18 - ADC1 global interrupt"]
    ADC = 18,
    #[doc = "19 - CAN1 TX interrupt"]
    CAN1_TX = 19,
    #[doc = "20 - CAN1 RX0 interrupt"]
    CAN1_RX0 = 20,
    #[doc = "21 - CAN1 RX1 interrupt"]
    CAN_RX1 = 21,
    #[doc = "22 - CAN1 SE interrupt"]
    CAN_SE = 22,
    #[doc = "23 - EXINT Line\\[9:5\\] interrupts"]
    EXINT9_5 = 23,
    #[doc = "24 - TMR1 brake interrupt and TMR9 global interrupt"]
    TMR1_BRK_TMR9 = 24,
    #[doc = "25 - TMR1 overflow interrupt and TMR10 global interrupt"]
    TMR1_OVF_TMR10 = 25,
    #[doc = "26 - TMR1 trigger and HALL interrupts and TMR11 global interrupt"]
    TMR1_TRG_HALL_TMR11 = 26,
    #[doc = "27 - TMR1 channel interrupt"]
    TMR1_CH = 27,
    #[doc = "28 - TMR2 global interrupt"]
    TMR2 = 28,
    #[doc = "29 - TMR3 global interrupt"]
    TMR3 = 29,
    #[doc = "30 - TMR4 global interrupt"]
    TMR4 = 30,
    #[doc = "31 - I2C1 event interrupt"]
    I2C1_EVT = 31,
    #[doc = "32 - I2C1 error interrupt"]
    I2C1_ERR = 32,
    #[doc = "33 - I2C2 event interrupt"]
    I2C2_EVT = 33,
    #[doc = "34 - I2C2 error interrupt"]
    I2C2_ERR = 34,
    #[doc = "35 - SPI1 global interrupt"]
    SPI1 = 35,
    #[doc = "36 - SPI2 global interrupt"]
    SPI2 = 36,
    #[doc = "37 - USART1 global interrupt"]
    USART1 = 37,
    #[doc = "38 - USART2 global interrupt"]
    USART2 = 38,
    #[doc = "39 - USART3 global interrupt"]
    USART3 = 39,
    #[doc = "40 - EXINT Line\\[15:10\\] interrupts"]
    EXINT15_10 = 40,
    #[doc = "41 - ERTC Alarm interrupt connect to EXINT line17"]
    ERTCALARM = 41,
    #[doc = "42 - OTGFS1_WKUP interrupt connect to EXINT line18"]
    OTGFS1_WKUP = 42,
    #[doc = "48 - XMC global interrupt"]
    XMC = 48,
    #[doc = "51 - SPI3 global interrupt"]
    SPI3 = 51,
    #[doc = "52 - USART4 global interrupt"]
    USART4 = 52,
    #[doc = "53 - USART5 global interrupt"]
    USART5 = 53,
    #[doc = "54 - TMR6 global interrupt"]
    TMR6 = 54,
    #[doc = "55 - TMR7 global interrupt"]
    TMR7 = 55,
    #[doc = "63 - CAN2 TX interrupt"]
    CAN2_TX = 63,
    #[doc = "64 - CAN2 RX0 interrupt"]
    CAN2_RX0 = 64,
    #[doc = "65 - CAN2 RX1 interrupt"]
    CAN2_RX1 = 65,
    #[doc = "66 - CAN2 SE interrupt"]
    CAN2_SE = 66,
    #[doc = "67 - USB On The Go FS global interrupt"]
    OTGFS1 = 67,
    #[doc = "71 - USART6 global interrupt"]
    USART6 = 71,
    #[doc = "72 - I2C3 event interrupt"]
    I2C3_EVT = 72,
    #[doc = "73 - I2C3 error interrupt"]
    I2C3_ERR = 73,
    #[doc = "82 - USART7 global interrupt"]
    USART7 = 82,
    #[doc = "83 - USART8 global interrupt"]
    USART8 = 83,
    #[doc = "91 - QSPI2 global interrupt"]
    QSPI2 = 91,
    #[doc = "92 - QSPI1 global interrupt"]
    QSPI1 = 92,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Flexible static memory controller"]
pub type XMC = crate::Periph<xmc::RegisterBlock, 0xa000_0000>;
impl core::fmt::Debug for XMC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("XMC").finish()
    }
}
#[doc = "Flexible static memory controller"]
pub mod xmc;
#[doc = "Power control"]
pub type PWC = crate::Periph<pwc::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for PWC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWC").finish()
    }
}
#[doc = "Power control"]
pub mod pwc;
#[doc = "Clock and reset management"]
pub type CRM = crate::Periph<crm::RegisterBlock, 0x4002_3800>;
impl core::fmt::Debug for CRM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRM").finish()
    }
}
#[doc = "Clock and reset management"]
pub mod crm;
#[doc = "General purpose I/Os"]
pub type GPIOA = crate::Periph<gpioa::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for GPIOA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOA").finish()
    }
}
#[doc = "General purpose I/Os"]
pub mod gpioa;
#[doc = "General purpose I/Os"]
pub type GPIOB = crate::Periph<gpioa::RegisterBlock, 0x4002_0400>;
impl core::fmt::Debug for GPIOB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOB").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpiob;
#[doc = "General purpose I/Os"]
pub type GPIOC = crate::Periph<gpioa::RegisterBlock, 0x4002_0800>;
impl core::fmt::Debug for GPIOC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOC").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpioc;
#[doc = "General purpose I/Os"]
pub type GPIOD = crate::Periph<gpioa::RegisterBlock, 0x4002_0c00>;
impl core::fmt::Debug for GPIOD {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOD").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpiod;
#[doc = "General purpose I/Os"]
pub type GPIOE = crate::Periph<gpioa::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for GPIOE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOE").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpioe;
#[doc = "General purpose I/Os"]
pub type GPIOF = crate::Periph<gpioa::RegisterBlock, 0x4002_1400>;
impl core::fmt::Debug for GPIOF {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOF").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpiof;
#[doc = "EXINT"]
pub type EXINT = crate::Periph<exint::RegisterBlock, 0x4001_3c00>;
impl core::fmt::Debug for EXINT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EXINT").finish()
    }
}
#[doc = "EXINT"]
pub mod exint;
#[doc = "DMA controller"]
pub type DMA1 = crate::Periph<dma1::RegisterBlock, 0x4002_6000>;
impl core::fmt::Debug for DMA1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA1").finish()
    }
}
#[doc = "DMA controller"]
pub mod dma1;
#[doc = "DMA controller"]
pub type DMA2 = crate::Periph<dma1::RegisterBlock, 0x4002_6400>;
impl core::fmt::Debug for DMA2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA2").finish()
    }
}
#[doc = "DMA controller"]
pub use self::dma1 as dma2;
#[doc = "Real-time clock"]
pub type ERTC = crate::Periph<ertc::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for ERTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ERTC").finish()
    }
}
#[doc = "Real-time clock"]
pub mod ertc;
#[doc = "Watchdog"]
pub type WDT = crate::Periph<wdt::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for WDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WDT").finish()
    }
}
#[doc = "Watchdog"]
pub mod wdt;
#[doc = "Window watchdog"]
pub type WWDT = crate::Periph<wwdt::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for WWDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WWDT").finish()
    }
}
#[doc = "Window watchdog"]
pub mod wwdt;
#[doc = "Advanced timer"]
pub type TMR1 = crate::Periph<tmr1::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for TMR1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR1").finish()
    }
}
#[doc = "Advanced timer"]
pub mod tmr1;
#[doc = "General purpose timer"]
pub type TMR2 = crate::Periph<tmr2::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for TMR2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR2").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr2;
#[doc = "General purpose timer"]
pub type TMR3 = crate::Periph<tmr3::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for TMR3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR3").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr3;
#[doc = "General purpose timer"]
pub type TMR4 = crate::Periph<tmr3::RegisterBlock, 0x4000_0800>;
impl core::fmt::Debug for TMR4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR4").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr3 as tmr4;
#[doc = "General purpose timer"]
pub type TMR9 = crate::Periph<tmr9::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for TMR9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR9").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr9;
#[doc = "General purpose timer"]
pub type TMR12 = crate::Periph<tmr9::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for TMR12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR12").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr9 as tmr12;
#[doc = "General purpose timer"]
pub type TMR10 = crate::Periph<tmr10::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for TMR10 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR10").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr10;
#[doc = "General purpose timer"]
pub type TMR11 = crate::Periph<tmr10::RegisterBlock, 0x4001_4800>;
impl core::fmt::Debug for TMR11 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR11").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr10 as tmr11;
#[doc = "General purpose timer"]
pub type TMR13 = crate::Periph<tmr10::RegisterBlock, 0x4000_1c00>;
impl core::fmt::Debug for TMR13 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR13").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr10 as tmr13;
#[doc = "General purpose timer"]
pub type TMR14 = crate::Periph<tmr10::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for TMR14 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR14").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr10 as tmr14;
#[doc = "Basic timer"]
pub type TMR6 = crate::Periph<tmr6::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for TMR6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR6").finish()
    }
}
#[doc = "Basic timer"]
pub mod tmr6;
#[doc = "Basic timer"]
pub type TMR7 = crate::Periph<tmr6::RegisterBlock, 0x4000_1400>;
impl core::fmt::Debug for TMR7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TMR7").finish()
    }
}
#[doc = "Basic timer"]
pub use self::tmr6 as tmr7;
#[doc = "HICK Auto Clock Calibration"]
pub type ACC = crate::Periph<acc::RegisterBlock, 0x4001_7400>;
impl core::fmt::Debug for ACC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ACC").finish()
    }
}
#[doc = "HICK Auto Clock Calibration"]
pub mod acc;
#[doc = "Inter-integrated circuit"]
pub type I2C1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "Inter-integrated circuit"]
pub mod i2c1;
#[doc = "Inter-integrated circuit"]
pub type I2C2 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2C2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C2").finish()
    }
}
#[doc = "Inter-integrated circuit"]
pub use self::i2c1 as i2c2;
#[doc = "Inter-integrated circuit"]
pub type I2C3 = crate::Periph<i2c1::RegisterBlock, 0x4000_5c00>;
impl core::fmt::Debug for I2C3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C3").finish()
    }
}
#[doc = "Inter-integrated circuit"]
pub use self::i2c1 as i2c3;
#[doc = "Serial peripheral interface"]
pub type SPI1 = crate::Periph<spi1::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub mod spi1;
#[doc = "Serial peripheral interface"]
pub type SPI2 = crate::Periph<spi1::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for SPI2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI2").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub use self::spi1 as spi2;
#[doc = "Serial peripheral interface"]
pub type SPI3 = crate::Periph<spi1::RegisterBlock, 0x4000_3c00>;
impl core::fmt::Debug for SPI3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI3").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub use self::spi1 as spi3;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART1 = crate::Periph<usart1::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for USART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART1").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub mod usart1;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART2 = crate::Periph<usart1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for USART2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART2").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart2;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART3 = crate::Periph<usart1::RegisterBlock, 0x4000_4800>;
impl core::fmt::Debug for USART3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART3").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart3;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART6 = crate::Periph<usart1::RegisterBlock, 0x4001_1400>;
impl core::fmt::Debug for USART6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART6").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart6;
#[doc = "Analog to digital converter"]
pub type ADC1 = crate::Periph<adc1::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for ADC1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC1").finish()
    }
}
#[doc = "Analog to digital converter"]
pub mod adc1;
#[doc = "ADC common area"]
pub type ADCCOM = crate::Periph<adccom::RegisterBlock, 0x4001_2300>;
impl core::fmt::Debug for ADCCOM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADCCOM").finish()
    }
}
#[doc = "ADC common area"]
pub mod adccom;
#[doc = "Can controller area network"]
pub type CAN1 = crate::Periph<can1::RegisterBlock, 0x4000_6400>;
impl core::fmt::Debug for CAN1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAN1").finish()
    }
}
#[doc = "Can controller area network"]
pub mod can1;
#[doc = "Can controller area network"]
pub type CAN2 = crate::Periph<can1::RegisterBlock, 0x4000_6800>;
impl core::fmt::Debug for CAN2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAN2").finish()
    }
}
#[doc = "Can controller area network"]
pub use self::can1 as can2;
#[doc = "Digital to analog converter"]
pub type DAC = crate::Periph<dac::RegisterBlock, 0x4000_7400>;
impl core::fmt::Debug for DAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC").finish()
    }
}
#[doc = "Digital to analog converter"]
pub mod dac;
#[doc = "Debug support"]
pub type DEBUG = crate::Periph<debug::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for DEBUG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DEBUG").finish()
    }
}
#[doc = "Debug support"]
pub mod debug;
#[doc = "Universal synchronous receiver transmitter"]
pub type USART4 = crate::Periph<usart1::RegisterBlock, 0x4000_4c00>;
impl core::fmt::Debug for USART4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART4").finish()
    }
}
#[doc = "Universal synchronous receiver transmitter"]
pub use self::usart1 as usart4;
#[doc = "Universal synchronous receiver transmitter"]
pub type USART5 = crate::Periph<usart1::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for USART5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART5").finish()
    }
}
#[doc = "Universal synchronous receiver transmitter"]
pub use self::usart1 as usart5;
#[doc = "Universal synchronous receiver transmitter"]
pub type USART7 = crate::Periph<usart1::RegisterBlock, 0x4000_7800>;
impl core::fmt::Debug for USART7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART7").finish()
    }
}
#[doc = "Universal synchronous receiver transmitter"]
pub use self::usart1 as usart7;
#[doc = "Universal synchronous receiver transmitter"]
pub type USART8 = crate::Periph<usart1::RegisterBlock, 0x4000_7c00>;
impl core::fmt::Debug for USART8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART8").finish()
    }
}
#[doc = "Universal synchronous receiver transmitter"]
pub use self::usart1 as usart8;
#[doc = "CRC calculation unit"]
pub type CRC = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for CRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRC").finish()
    }
}
#[doc = "CRC calculation unit"]
pub mod crc;
#[doc = "Flash memory controler"]
pub type FLASH = crate::Periph<flash::RegisterBlock, 0x4002_3c00>;
impl core::fmt::Debug for FLASH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FLASH").finish()
    }
}
#[doc = "Flash memory controler"]
pub mod flash;
#[doc = "USB on-the-go full speed"]
pub type USB_OTGFS_GLOBAL = crate::Periph<usb_otgfs_global::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for USB_OTGFS_GLOBAL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB_OTGFS_GLOBAL").finish()
    }
}
#[doc = "USB on-the-go full speed"]
pub mod usb_otgfs_global;
#[doc = "USB on the go full speed"]
pub type USB_OTGFS_HOST = crate::Periph<usb_otgfs_host::RegisterBlock, 0x5000_0400>;
impl core::fmt::Debug for USB_OTGFS_HOST {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB_OTGFS_HOST").finish()
    }
}
#[doc = "USB on the go full speed"]
pub mod usb_otgfs_host;
#[doc = "USB on the go full speed"]
pub type USB_OTGFS_DEVICE = crate::Periph<usb_otgfs_device::RegisterBlock, 0x5000_0800>;
impl core::fmt::Debug for USB_OTGFS_DEVICE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB_OTGFS_DEVICE").finish()
    }
}
#[doc = "USB on the go full speed"]
pub mod usb_otgfs_device;
#[doc = "USB on the go full speed"]
pub type USB_OTGFS_PWRCLK = crate::Periph<usb_otgfs_pwrclk::RegisterBlock, 0x5000_0e00>;
impl core::fmt::Debug for USB_OTGFS_PWRCLK {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB_OTGFS_PWRCLK").finish()
    }
}
#[doc = "USB on the go full speed"]
pub mod usb_otgfs_pwrclk;
#[doc = "System configuration controller"]
pub type SCFG = crate::Periph<scfg::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for SCFG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SCFG").finish()
    }
}
#[doc = "System configuration controller"]
pub mod scfg;
#[doc = "Quad SPI Controller"]
pub type QSPI1 = crate::Periph<qspi1::RegisterBlock, 0xa000_1000>;
impl core::fmt::Debug for QSPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QSPI1").finish()
    }
}
#[doc = "Quad SPI Controller"]
pub mod qspi1;
#[doc = "Quad SPI Controller"]
pub type QSPI2 = crate::Periph<qspi1::RegisterBlock, 0xa000_2000>;
impl core::fmt::Debug for QSPI2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QSPI2").finish()
    }
}
#[doc = "Quad SPI Controller"]
pub use self::qspi1 as qspi2;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "XMC"]
    pub XMC: XMC,
    #[doc = "PWC"]
    pub PWC: PWC,
    #[doc = "CRM"]
    pub CRM: CRM,
    #[doc = "GPIOA"]
    pub GPIOA: GPIOA,
    #[doc = "GPIOB"]
    pub GPIOB: GPIOB,
    #[doc = "GPIOC"]
    pub GPIOC: GPIOC,
    #[doc = "GPIOD"]
    pub GPIOD: GPIOD,
    #[doc = "GPIOE"]
    pub GPIOE: GPIOE,
    #[doc = "GPIOF"]
    pub GPIOF: GPIOF,
    #[doc = "EXINT"]
    pub EXINT: EXINT,
    #[doc = "DMA1"]
    pub DMA1: DMA1,
    #[doc = "DMA2"]
    pub DMA2: DMA2,
    #[doc = "ERTC"]
    pub ERTC: ERTC,
    #[doc = "WDT"]
    pub WDT: WDT,
    #[doc = "WWDT"]
    pub WWDT: WWDT,
    #[doc = "TMR1"]
    pub TMR1: TMR1,
    #[doc = "TMR2"]
    pub TMR2: TMR2,
    #[doc = "TMR3"]
    pub TMR3: TMR3,
    #[doc = "TMR4"]
    pub TMR4: TMR4,
    #[doc = "TMR9"]
    pub TMR9: TMR9,
    #[doc = "TMR12"]
    pub TMR12: TMR12,
    #[doc = "TMR10"]
    pub TMR10: TMR10,
    #[doc = "TMR11"]
    pub TMR11: TMR11,
    #[doc = "TMR13"]
    pub TMR13: TMR13,
    #[doc = "TMR14"]
    pub TMR14: TMR14,
    #[doc = "TMR6"]
    pub TMR6: TMR6,
    #[doc = "TMR7"]
    pub TMR7: TMR7,
    #[doc = "ACC"]
    pub ACC: ACC,
    #[doc = "I2C1"]
    pub I2C1: I2C1,
    #[doc = "I2C2"]
    pub I2C2: I2C2,
    #[doc = "I2C3"]
    pub I2C3: I2C3,
    #[doc = "SPI1"]
    pub SPI1: SPI1,
    #[doc = "SPI2"]
    pub SPI2: SPI2,
    #[doc = "SPI3"]
    pub SPI3: SPI3,
    #[doc = "USART1"]
    pub USART1: USART1,
    #[doc = "USART2"]
    pub USART2: USART2,
    #[doc = "USART3"]
    pub USART3: USART3,
    #[doc = "USART6"]
    pub USART6: USART6,
    #[doc = "ADC1"]
    pub ADC1: ADC1,
    #[doc = "ADCCOM"]
    pub ADCCOM: ADCCOM,
    #[doc = "CAN1"]
    pub CAN1: CAN1,
    #[doc = "CAN2"]
    pub CAN2: CAN2,
    #[doc = "DAC"]
    pub DAC: DAC,
    #[doc = "DEBUG"]
    pub DEBUG: DEBUG,
    #[doc = "USART4"]
    pub USART4: USART4,
    #[doc = "USART5"]
    pub USART5: USART5,
    #[doc = "USART7"]
    pub USART7: USART7,
    #[doc = "USART8"]
    pub USART8: USART8,
    #[doc = "CRC"]
    pub CRC: CRC,
    #[doc = "FLASH"]
    pub FLASH: FLASH,
    #[doc = "USB_OTGFS_GLOBAL"]
    pub USB_OTGFS_GLOBAL: USB_OTGFS_GLOBAL,
    #[doc = "USB_OTGFS_HOST"]
    pub USB_OTGFS_HOST: USB_OTGFS_HOST,
    #[doc = "USB_OTGFS_DEVICE"]
    pub USB_OTGFS_DEVICE: USB_OTGFS_DEVICE,
    #[doc = "USB_OTGFS_PWRCLK"]
    pub USB_OTGFS_PWRCLK: USB_OTGFS_PWRCLK,
    #[doc = "SCFG"]
    pub SCFG: SCFG,
    #[doc = "QSPI1"]
    pub QSPI1: QSPI1,
    #[doc = "QSPI2"]
    pub QSPI2: QSPI2,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            XMC: XMC::steal(),
            PWC: PWC::steal(),
            CRM: CRM::steal(),
            GPIOA: GPIOA::steal(),
            GPIOB: GPIOB::steal(),
            GPIOC: GPIOC::steal(),
            GPIOD: GPIOD::steal(),
            GPIOE: GPIOE::steal(),
            GPIOF: GPIOF::steal(),
            EXINT: EXINT::steal(),
            DMA1: DMA1::steal(),
            DMA2: DMA2::steal(),
            ERTC: ERTC::steal(),
            WDT: WDT::steal(),
            WWDT: WWDT::steal(),
            TMR1: TMR1::steal(),
            TMR2: TMR2::steal(),
            TMR3: TMR3::steal(),
            TMR4: TMR4::steal(),
            TMR9: TMR9::steal(),
            TMR12: TMR12::steal(),
            TMR10: TMR10::steal(),
            TMR11: TMR11::steal(),
            TMR13: TMR13::steal(),
            TMR14: TMR14::steal(),
            TMR6: TMR6::steal(),
            TMR7: TMR7::steal(),
            ACC: ACC::steal(),
            I2C1: I2C1::steal(),
            I2C2: I2C2::steal(),
            I2C3: I2C3::steal(),
            SPI1: SPI1::steal(),
            SPI2: SPI2::steal(),
            SPI3: SPI3::steal(),
            USART1: USART1::steal(),
            USART2: USART2::steal(),
            USART3: USART3::steal(),
            USART6: USART6::steal(),
            ADC1: ADC1::steal(),
            ADCCOM: ADCCOM::steal(),
            CAN1: CAN1::steal(),
            CAN2: CAN2::steal(),
            DAC: DAC::steal(),
            DEBUG: DEBUG::steal(),
            USART4: USART4::steal(),
            USART5: USART5::steal(),
            USART7: USART7::steal(),
            USART8: USART8::steal(),
            CRC: CRC::steal(),
            FLASH: FLASH::steal(),
            USB_OTGFS_GLOBAL: USB_OTGFS_GLOBAL::steal(),
            USB_OTGFS_HOST: USB_OTGFS_HOST::steal(),
            USB_OTGFS_DEVICE: USB_OTGFS_DEVICE::steal(),
            USB_OTGFS_PWRCLK: USB_OTGFS_PWRCLK::steal(),
            SCFG: SCFG::steal(),
            QSPI1: QSPI1::steal(),
            QSPI2: QSPI2::steal(),
        }
    }
}
